[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jaXRD"
version = "0.1.0"
description = "Powder diffraction refinement in JAX"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "numpy",
  "jax",
  "pymatgen",
  "equinox",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["jaxrd*"]
